name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  detect-noop:
    runs-on: ubuntu-latest
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect no-op changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          paths_ignore: '["**.md"]'
          concurrent_skipping: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: detect-noop
    if: ${{ needs.detect-noop.outputs.noop != 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: make docker-build

      - name: Build bundle
        run: make bundle-build

  bundle:
    name: Check diff
    runs-on: ubuntu-latest
    needs: detect-noop
    if: ${{ needs.detect-noop.outputs.noop != 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate bundle
        run: make bundle

      - name: Check diff
        uses: mmontes11/diff-porcelain@v0.0.1
        with:
          message: Bundle is not up to date. Run 'make bundle' and commit the changes.
